
CREATE TABLE banks (
    bank_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_name VARCHAR2(100) NOT NULL
);

CREATE TABLE reviews (
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id NUMBER REFERENCES banks(bank_id),
    review_text CLOB,
    rating NUMBER,
    review_date DATE,
    sentiment_label VARCHAR2(20),
    sentiment_score NUMBER,
    theme VARCHAR2(100)
);

ALTER TABLE reviews ADD CONSTRAINT rating_check CHECK (rating BETWEEN 1 AND 5);
SELECT * FROM banks;
SELECT * FROM reviews;